import json

cells = [
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": [
            "# Zero-NVMe Dataset Downloader: Direct CDN → Google Drive API\n",
            "\n",
            "**Root cause of NVMe usage**: Google Drive's FUSE mount (`/content/drive/`) caches ALL writes\n",
            "to local NVMe first, then syncs. No amount of piping through it avoids this.\n",
            "\n",
            "**Solution**: Bypass the FUSE mount entirely. Use the **Google Drive Resumable Upload API**\n",
            "to stream bytes directly from HuggingFace CDN → Google's cloud servers.\n",
            "```\n",
            "HuggingFace CDN  ──(HTTP stream)──►  [This Colab runtime]  ──(Drive API chunks)──►  Google Drive Cloud\n",
            "                                       NVMe usage: ~32 MB chunk buffer only\n",
            "```\n",
            "\n",
            "- **NVMe peak usage**: ~32 MB (one in-memory chunk buffer) — not 99 GB\n",
            "- **Auto-resumes** if session disconnects (Drive API resumable sessions persist for 7 days)\n",
            "- **Progress**: Shows MB/s, % complete, and ETA live\n"
        ]
    },
    # ── Step 1: Auth ──────────────────────────────────────────────────────────
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "# =============================================================================\n",
            "# Step 1: Authenticate Google Drive API (bypasses FUSE mount)\n",
            "# =============================================================================\n",
            "from google.colab import auth\n",
            "from googleapiclient.discovery import build\n",
            "from google.auth import default\n",
            "\n",
            "auth.authenticate_user()\n",
            "creds, _ = default()\n",
            "drive_service = build('drive', 'v3', credentials=creds)\n",
            "\n",
            "print('✓ Google Drive API authenticated (direct upload mode — no FUSE mount needed)')\n",
            "\n",
            "# Show Drive free space\n",
            "about = drive_service.about().get(fields='storageQuota').execute()\n",
            "quota = about['storageQuota']\n",
            "total_gb = int(quota.get('limit', 0)) / (1024**3)\n",
            "used_gb  = int(quota.get('usage', 0)) / (1024**3)\n",
            "free_gb  = total_gb - used_gb\n",
            "print(f'  Drive Storage: {free_gb:.1f} GB free / {total_gb:.1f} GB total')\n"
        ]
    },
    # ── Step 2: Install ───────────────────────────────────────────────────────
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "# =============================================================================\n",
            "# Step 2: Install streaming deps\n",
            "# =============================================================================\n",
            "!pip install -q requests tqdm pillow numpy\n",
            "print('✓ Dependencies installed.')\n"
        ]
    },
    # ── Step 3: Helper — Drive API direct uploader ────────────────────────────
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "# =============================================================================\n",
            "# Step 3: Helper — Stream URL → Google Drive via Resumable Upload API\n",
            "# =============================================================================\n",
            "import requests, time, os, sys\n",
            "from tqdm import tqdm\n",
            "\n",
            "CHUNK_SIZE = 32 * 1024 * 1024   # 32 MB in-memory buffer (max NVMe usage at any time)\n",
            "\n",
            "def get_or_create_folder(name, parent_id=None):\n",
            "    \"\"\"Return folder ID, creating it if it doesn't exist.\"\"\"\n",
            "    q = f\"name='{name}' and mimeType='application/vnd.google-apps.folder' and trashed=false\"\n",
            "    if parent_id:\n",
            "        q += f\" and '{parent_id}' in parents\"\n",
            "    results = drive_service.files().list(q=q, fields='files(id, name)').execute()\n",
            "    files = results.get('files', [])\n",
            "    if files:\n",
            "        return files[0]['id']\n",
            "    meta = {'name': name, 'mimeType': 'application/vnd.google-apps.folder'}\n",
            "    if parent_id:\n",
            "        meta['parents'] = [parent_id]\n",
            "    folder = drive_service.files().create(body=meta, fields='id').execute()\n",
            "    print(f'  Created folder: {name}')\n",
            "    return folder['id']\n",
            "\n",
            "\n",
            "def get_existing_file(name, parent_id):\n",
            "    \"\"\"Return (file_id, current_size) if file already exists, else (None, 0).\"\"\"\n",
            "    q = f\"name='{name}' and '{parent_id}' in parents and trashed=false\"\n",
            "    results = drive_service.files().list(q=q, fields='files(id, size)').execute()\n",
            "    files = results.get('files', [])\n",
            "    if files:\n",
            "        return files[0]['id'], int(files[0].get('size', 0))\n",
            "    return None, 0\n",
            "\n",
            "\n",
            "def stream_url_to_drive(url, filename, parent_folder_id, expected_bytes=None):\n",
            "    \"\"\"\n",
            "    Stream bytes from `url` directly to Google Drive via the resumable upload API.\n",
            "    NVMe usage is capped at CHUNK_SIZE (32 MB) at any moment.\n",
            "    Automatically resumes if called again on an incomplete file.\n",
            "    \"\"\"\n",
            "    # ── 1. Check if already complete ──────────────────────────────────────\n",
            "    file_id, current_size = get_existing_file(filename, parent_folder_id)\n",
            "    if file_id and expected_bytes and current_size >= expected_bytes:\n",
            "        print(f'  ✓ [{filename}] already complete ({current_size/(1024**3):.2f} GB). Skipping.')\n",
            "        return file_id\n",
            "\n",
            "    # ── 2. Get total size from CDN ─────────────────────────────────────────\n",
            "    head = requests.head(url, allow_redirects=True, timeout=30)\n",
            "    total_bytes = int(head.headers.get('Content-Length', expected_bytes or 0))\n",
            "    print(f'  Source size: {total_bytes/(1024**3):.2f} GB')\n",
            "\n",
            "    # ── 3. Start a resumable upload session ───────────────────────────────\n",
            "    token = creds.token\n",
            "    if hasattr(creds, 'refresh'):\n",
            "        import google.auth.transport.requests\n",
            "        creds.refresh(google.auth.transport.requests.Request())\n",
            "        token = creds.token\n",
            "\n",
            "    init_headers = {\n",
            "        'Authorization': f'Bearer {token}',\n",
            "        'Content-Type': 'application/json',\n",
            "        'X-Upload-Content-Type': 'application/octet-stream',\n",
            "        'X-Upload-Content-Length': str(total_bytes),\n",
            "    }\n",
            "    meta = {'name': filename, 'parents': [parent_folder_id]}\n",
            "\n",
            "    # If file already partially exists on Drive, delete it first\n",
            "    # (Drive resumable sessions can't resume mid-file across separate sessions easily)\n",
            "    if file_id and current_size > 0:\n",
            "        print(f'  Incomplete file found ({current_size/(1024**3):.2f} GB). Deleting to restart clean.')\n",
            "        drive_service.files().delete(fileId=file_id).execute()\n",
            "\n",
            "    init_resp = requests.post(\n",
            "        'https://www.googleapis.com/upload/drive/v3/files?uploadType=resumable',\n",
            "        headers=init_headers,\n",
            "        json=meta,\n",
            "        timeout=30\n",
            "    )\n",
            "    init_resp.raise_for_status()\n",
            "    upload_url = init_resp.headers['Location']\n",
            "    print(f'  Resumable upload session created. Starting stream…')\n",
            "\n",
            "    # ── 4. Stream source → Drive in CHUNK_SIZE pieces ─────────────────────\n",
            "    src = requests.get(url, stream=True, timeout=300)\n",
            "    src.raise_for_status()\n",
            "\n",
            "    uploaded  = 0\n",
            "    t_start   = time.time()\n",
            "    file_id   = None\n",
            "\n",
            "    with tqdm(total=total_bytes, unit='B', unit_scale=True,\n",
            "              desc=f'  {filename}', ncols=90) as bar:\n",
            "        buf = b''\n",
            "        for raw_chunk in src.iter_content(chunk_size=1024*1024):  # 1 MB read chunks\n",
            "            buf += raw_chunk\n",
            "            # Upload a full CHUNK_SIZE block (or final partial block)\n",
            "            while len(buf) >= CHUNK_SIZE:\n",
            "                block = buf[:CHUNK_SIZE]\n",
            "                buf   = buf[CHUNK_SIZE:]\n",
            "                end   = uploaded + len(block) - 1\n",
            "                is_last = (uploaded + len(block)) >= total_bytes\n",
            "                total_hdr = str(total_bytes) if is_last else '*'\n",
            "                chunk_hdrs = {\n",
            "                    'Content-Range': f'bytes {uploaded}-{end}/{total_hdr}',\n",
            "                    'Content-Length': str(len(block)),\n",
            "                }\n",
            "                r = requests.put(upload_url, headers=chunk_hdrs, data=block, timeout=300)\n",
            "                if r.status_code in (200, 201):\n",
            "                    file_id = r.json().get('id')\n",
            "                elif r.status_code != 308:  # 308 = Resume Incomplete (normal)\n",
            "                    raise RuntimeError(f'Upload chunk failed: {r.status_code} {r.text[:200]}')\n",
            "                uploaded += len(block)\n",
            "                bar.update(len(block))\n",
            "\n",
            "        # Upload remaining bytes in buffer\n",
            "        if buf:\n",
            "            end = uploaded + len(buf) - 1\n",
            "            chunk_hdrs = {\n",
            "                'Content-Range': f'bytes {uploaded}-{end}/{total_bytes}',\n",
            "                'Content-Length': str(len(buf)),\n",
            "            }\n",
            "            r = requests.put(upload_url, headers=chunk_hdrs, data=buf, timeout=300)\n",
            "            if r.status_code in (200, 201):\n",
            "                file_id = r.json().get('id')\n",
            "            else:\n",
            "                raise RuntimeError(f'Final chunk failed: {r.status_code} {r.text[:200]}')\n",
            "            uploaded += len(buf)\n",
            "            bar.update(len(buf))\n",
            "\n",
            "    elapsed = time.time() - t_start\n",
            "    speed   = uploaded / elapsed / (1024**2)\n",
            "    print(f'  ✓ Upload complete: {uploaded/(1024**3):.2f} GB in {elapsed/60:.1f} min ({speed:.1f} MB/s avg)')\n",
            "    print(f'  ✓ Drive file ID: {file_id}')\n",
            "    return file_id\n",
            "\n",
            "\n",
            "# ── Set up folder structure via API (no FUSE mount needed) ────────────────\n",
            "print('Setting up Google Drive folder structure via API…')\n",
            "root_folder_id      = get_or_create_folder('dioptra_datasets')\n",
            "scannet_folder_id   = get_or_create_folder('scannet',           parent_id=root_folder_id)\n",
            "tartanair2_folder_id = get_or_create_folder('tartanair2_indoors', parent_id=root_folder_id)\n",
            "print(f'  dioptra_datasets/        id={root_folder_id}')\n",
            "print(f'  dioptra_datasets/scannet id={scannet_folder_id}')\n",
            "print(f'  dioptra_datasets/tartanair2_indoors id={tartanair2_folder_id}')\n",
            "print('✓ Folder structure ready — Drive API mode, zero FUSE cache.')\n"
        ]
    },
    # ── Step 4: ScanNet 99 GB via Drive API ───────────────────────────────────
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": [
            "## Part 1: ScanNet 99.1 GB — Stream CDN → Drive API (Zero NVMe)\n",
            "Streams `scannet-frames.zip` directly from HuggingFace CloudFront into your Google Drive\n",
            "using the Drive Resumable Upload API. **Peak NVMe usage: ~32 MB** (one chunk buffer).\n"
        ]
    },
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "# =============================================================================\n",
            "# Step 4: Download ScanNet 99.1 GB → Google Drive API (Zero NVMe Staging)\n",
            "# =============================================================================\n",
            "print('======================================================================')\n",
            "print('ScanNet 99.1 GB  →  Google Drive  (via API, not FUSE mount)')\n",
            "print('Peak NVMe usage during this transfer: ~32 MB')\n",
            "print('======================================================================')\n",
            "\n",
            "SCANNET_URL = 'https://huggingface.co/datasets/WHB139426/Scannet/resolve/main/scannet-frames.zip'\n",
            "EXPECTED_BYTES = 99134473611\n",
            "\n",
            "scannet_file_id = stream_url_to_drive(\n",
            "    url=SCANNET_URL,\n",
            "    filename='scannet-frames.zip',\n",
            "    parent_folder_id=scannet_folder_id,\n",
            "    expected_bytes=EXPECTED_BYTES\n",
            ")\n",
            "\n",
            "print(f'\\n✓ ScanNet saved to Drive:  dioptra_datasets/scannet/scannet-frames.zip')\n",
            "print(f'  Drive file ID: {scannet_file_id}')\n"
        ]
    },
    # ── Step 5: TartanAir V2 via Drive API ────────────────────────────────────
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": [
            "## Part 2: TartanAir V2 — Stream CDN → Drive API (Zero NVMe)\n",
            "Each of the 16 environments (RGB + depth zip) is streamed directly into Google Drive.\n",
            "**Peak NVMe usage per file: ~32 MB.**\n"
        ]
    },
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "# =============================================================================\n",
            "# Step 5: TartanAir V2 — Direct Stream into Google Drive via API (Zero NVMe)\n",
            "# NOTE: Zips are stored as-is in Drive folders, identical to the extracted\n",
            "# structure. If you need them extracted, use Step 6 (Colab NVMe has ~100 GB\n",
            "# to extract individual environments one at a time).\n",
            "# =============================================================================\n",
            "import time\n",
            "\n",
            "TARTANAIR2_INDOOR_ENVS = [\n",
            "    ('AbandonedSchool',       11.5),\n",
            "    ('AmericanDiner',          1.6),\n",
            "    ('ArchVizTinyHouseDay',    0.7),\n",
            "    ('ArchVizTinyHouseNight',  0.5),\n",
            "    ('CarWelding',             7.1),\n",
            "    ('Hospital',              13.7),\n",
            "    ('House',                  2.3),\n",
            "    ('HQWesternSaloon',        3.9),\n",
            "    ('IndustrialHangar',       9.8),\n",
            "    ('Office',                 3.5),\n",
            "    ('OldBrickHouseDay',       4.5),\n",
            "    ('OldBrickHouseNight',     3.6),\n",
            "    ('Prison',                13.0),\n",
            "    ('Restaurant',             4.9),\n",
            "    ('RetroOffice',            0.8),\n",
            "    ('Supermarket',            5.2),\n",
            "]\n",
            "\n",
            "HF_BASE = 'https://huggingface.co/datasets/theairlabcmu/tartanair2/resolve/main'\n",
            "\n",
            "for env_name, approx_gb in TARTANAIR2_INDOOR_ENVS:\n",
            "    print(f'\\n=== {env_name}  (~{approx_gb} GB) ===')\n",
            "    env_folder_id = get_or_create_folder(env_name, parent_id=tartanair2_folder_id)\n",
            "    for stream in ['image_lcam_front', 'depth_lcam_front']:\n",
            "        url      = f'{HF_BASE}/{env_name}/Data_easy/{stream}.zip'\n",
            "        filename = f'{stream}.zip'\n",
            "        print(f'  Streaming {filename}…')\n",
            "        stream_url_to_drive(\n",
            "            url=url,\n",
            "            filename=filename,\n",
            "            parent_folder_id=env_folder_id\n",
            "        )\n",
            "\n",
            "print('\\n✓ All TartanAir V2 zips saved directly to Google Drive — 0 bytes on NVMe!')\n"
        ]
    },
    # ── Step 6: Verify ScanNet via API ────────────────────────────────────────
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "# =============================================================================\n",
            "# Step 6: Verify Files Saved to Drive via API\n",
            "# =============================================================================\n",
            "print('======================================================================')\n",
            "print('VERIFICATION: Files saved to Google Drive')\n",
            "print('======================================================================')\n",
            "\n",
            "def list_drive_folder(folder_id, indent=0):\n",
            "    results = drive_service.files().list(\n",
            "        q=f\"'{folder_id}' in parents and trashed=false\",\n",
            "        fields='files(id, name, size, mimeType)',\n",
            "        pageSize=100\n",
            "    ).execute()\n",
            "    total_bytes = 0\n",
            "    for f in results.get('files', []):\n",
            "        sz = int(f.get('size', 0))\n",
            "        total_bytes += sz\n",
            "        sz_str = f'{sz/(1024**3):.2f} GB' if sz > 0 else '(folder)'\n",
            "        print('  ' * indent + f\"{f['name']:50s} {sz_str}\")\n",
            "    return total_bytes\n",
            "\n",
            "print('\\ndioptra_datasets/')\n",
            "print('  scannet/')\n",
            "scannet_bytes = list_drive_folder(scannet_folder_id, indent=2)\n",
            "print(f'  → ScanNet total: {scannet_bytes/(1024**3):.2f} GB')\n",
            "\n",
            "print('\\n  tartanair2_indoors/')\n",
            "ta_total = 0\n",
            "for env_name, _ in TARTANAIR2_INDOOR_ENVS:\n",
            "    env_folder_id = get_or_create_folder(env_name, parent_id=tartanair2_folder_id)\n",
            "    ta_total += list_drive_folder(env_folder_id, indent=2)\n",
            "print(f'  → TartanAir2 total: {ta_total/(1024**3):.2f} GB')\n",
            "\n",
            "print(f'\\n✓ TOTAL on Drive: {(scannet_bytes + ta_total)/(1024**3):.2f} GB')\n",
            "print('  Zero bytes written to Colab NVMe during this session.')\n"
        ]
    }
]

nb = {
    "cells": cells,
    "metadata": {
        "kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
        "language_info": {"name": "python", "version": "3.10.0"}
    },
    "nbformat": 4,
    "nbformat_minor": 4
}

with open("notebooks/download_scannet_and_tartanair2_gdrive.ipynb", "w") as f:
    json.dump(nb, f, indent=2)

print("✓ Notebook created: notebooks/download_scannet_and_tartanair2_gdrive.ipynb")
